# Configurations
title:            IMTechEd
longtitle:        IMTechEd
author:           J. Austin Straley, DO
email:            imteched@gmail.com
description: >
  A website detailing my past, present, and future work.

version:          1.0
gitbook_version:  3.2.3

url:              'www.imteched.com'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

download: null

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

cardiology: [ACS,
              Congenital,
              Consults,
              Critical Care,
              Echo,
              EKG,
              EP,
              Heart Failure,
              Imaging,
              Invasive Cardiology,
              Medications,
              Nuclear,
              Other,
              Pericardial Disease,
              Prevention,
              Reasarch,
              Stable Ischemic Disease,
              Vascular,
              Valvular Heart Disease]
medications: [Autonomics,
                Blood & Anti-Inflammatories, 
                Cardiovascular-Renal, 
                Chemotherapy & ID, 
                Endocrine, 
                Nervous System, 
                Psychiatry, 
                Smooth Muscle, 
                Special Topics, 
                Toxicology, 
                Labs and Side Effects,
                Other]
notes: [Dotphrases,
          Lectures,
          Note Writing,
          Other,
          Resources]
topics: [Cardiology,
                Dermatology,
                Endocrinology,
                Gastroenterology,
                General,
                Geriatrics,
                Hematology,
                Infectious Disease,
                Neurology,
                Nephrology,
                Oncology,
                Pulmonology/ICU,
                Rheumatology,
                Medications
                ]

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    sort_by: date
    sequence: 1
  msqt:
    chapter:
      lesson: true
    output: true
    permalink: /:collection/:path/
    sort_by: chapter
  internguidepages:
    chapter:
      lesson: true
    output: false
    permalink: /:collection/:path/
    sort_by: chapter
  mcspages:
    chapter:
      lesson: true
    output: true
    posts_limit: 3
    permalink: /:collection/:path/
    sort_by: chapter
  internguidepages:
    chapter:
      lesson: true
    output: false
    permalink: /:collection/:path/
    sort_by: chapter
    sequence: 5
  feed:
    output: true
    permalink: /:collection/:path/
    tags: true
    posts_limit: 5
    sort_by: lesson
  posts:
    output: true
    permalink: /:collection/:path/
    sort_by: title
    sequence: 3
  resources:
    output: true
    permalink: /:collection/:path/
    sort_by: importance
    sequence: 4

destination:      ./_site
incremental:      false
regenerate:       true

page_width: 900px

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-remote-theme

tracker:
  google_analytics: "G-DRP25XGTN2"