# Configurations
title:            IMTechEd
longtitle:        IMTechEd
author:           J. Austin Straley, DO
email:            imteched@gmail.com
description: >
  A website detailing my past, present, and future work.

version:          1.0
gitbook_version:  3.2.3

url:              'www.imteched.com'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3
  collapse: subsection

download: null

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

# Collections
collections:
  internguidepages:
    chapter:
      lesson: true
    output: true
    permalink: /:collection/:path/
    sort_by: chapter
  mcspages:
    chapter:
      lesson: true
    output: true
    permalink: /:collection/:path/
    sort_by: chapter
  feed:
    output: true
    permalink: /:collection/:path/
    tags: true
    catagories:
        - news
        - updates
        - internguidepages
        - mcspages
        - projects
    posts_limit: 5
    sort_by: lesson
  pages:
    output: true
    permalink: /:collection/:path/
    sort_by: date
  posts:
    output: true
    permalink: /:collection/:path/
    sort_by: title

destination:      ./_site
incremental:      false
regenerate:       true

page_width: 800px

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

tracker:
  google_analytics: "G-DRP25XGTN2"

#- name: Deploy to Firebase Hosting
 # uses: FirebaseExtended/action-hosting-deploy@v0
